[package]
name = "day17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = { workspace = true }
nom = { workspace = true }
itertools = { workspace = true }
z3 = "*"